apiVersion: v2
name: calendso
description: A helm chart for calendso
version: 0.1.0
appVersion: 0.1.22
dependencies:
- name: calendso
  version: 0.1.22
  repository: cm://app.plural.sh/cm/calendso
  condition: calendso.enabled
